name: ticket_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0+8.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Standard Packages ---
  cupertino_icons: ^1.0.8
  http: ^1.5.0         # âœ… à¸à¸¥à¸±à¸šà¸¡à¸²à¹ƒà¸Šà¹‰à¸•à¸±à¸§à¸¥à¹ˆà¸²à¸ªà¸¸à¸”à¹„à¸”à¹‰à¹à¸¥à¹‰à¸§
  flutter_dotenv: ^6.0.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.2
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  
  # --- Utils ---
  flutter_secure_storage: ^9.2.4
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  fl_chart: ^0.66.0
  image: ^4.0.17
  # --- Printer Hardware ---
  imin_printer: ^0.6.14
  image_picker: ^1.1.2  # à»€àºžàºµà»ˆàº¡àº•àº»àº§àº™àºµà»‰
  path_provider: ^2.1.5
  
  # ðŸ‘‡ à¸žà¸£à¸°à¹€à¸­à¸à¸„à¸™à¹ƒà¸«à¸¡à¹ˆ (à¹€à¸šà¸² à¹à¸¥à¸°à¹„à¸¡à¹ˆà¸•à¸µà¸à¸±à¸šà¹ƒà¸„à¸£)
  flutter_usb_printer: ^0.1.0+1
  mobile_scanner: ^7.1.3
  webview_flutter: ^4.13.0

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # âœ… à¸à¸¥à¸±à¸šà¸¡à¸²à¹ƒà¸Šà¹‰à¸•à¸±à¸§à¸¥à¹ˆà¸²à¸ªà¸¸à¸”à¹„à¸”à¹‰à¹à¸¥à¹‰à¸§

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
    - assets/fonts/Phetsarath_OT.ttf
    - assets/manual.html
    - assets/images/bank_qr_cropped.jpeg
  fonts:
    - family: Phetsarath_OT
      fonts:
        - asset: assets/fonts/Phetsarath_OT.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resoluti  on-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
